# Generated by Django 2.2.7 on 2019-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(blank=True, max_length=150, verbose_name='表示名'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=200, verbose_name='プロフィール'),
        ),
    ]
